### ISSUE TITLE
installation of kinova Jaco2 SDK 1.4

### ISSUE THREAD

**Issue by huiwenzhang** [Kinovarobotics/kinova-ros#188]
Hi, 
The latest version of the Jaco2 sdk is 1.4. I used the 1.0 version SDK before. Now I want to update it . I download the software from the official web. However, I can't install it. It stucks at the beginning of the installation. I want to does it anyone tried the latest SDK?  Why installation failed ? Does the latest SDK compatible with this ROS package?
Thanks

**Comment by martine1406** [comment]
Hi @huiwenzhang

The installation is probably stuck because on Ubuntu, you need to run the installer in sudo. i.e. you cd in the folder where you can find the installer.sh file, then run sudo ./"this installer file".sh

The latest SDK is compatible with this ROS package. 
This issue is not specific to this package so please write to support@kinova.ca if you still have trouble. 
Thank you
Martine
