### ISSUE TITLE
How many points in trajectory are reasonable

### ISSUE THREAD

**Issue by robertbeach** [Kinovarobotics/kinova-ros#200]
I am using a Jaco2 arm on Moveit/indigo/14.04 (all standard stuff). I have a small program written in Python that moves the arm in a simple box like movement (left, down, right, up) with the typical movement of about 3" in the horizontal (X) range and 8" in the vertical (Z) range. The Y range does not change. 

I am finding that Trac_ik is generating between 10 and 50 points for virtually the same movement distance. The number of points generated seems pretty random although it seems that I either get 10 points or something above 30.  I have the solve type set to Manipulate2 (also tried Speed, Distance with no change in behavior).  The 10 point behavior generates nice movement that has little error while points above 20 or so generate odd, extreme arm movements that seem to end somewhat far (6+") from the goal. When that happens I replan to the original destination but it may still take 3-4 attempts to get to the correct goal.

I have tried filtering out plans with too many points but it can take 10 or more attempts to get a reasonable set of points and even that number of attempts may not yield a good count. 

Is this normal behavior or am I doing something really wrong

Thanks

**Comment by sbrisebois** [comment]
Hi,

I think that your arm might be in service mode. This may cause that kind of issues...
To put it in service mode please use the attached files: 
On Ubuntu place the file in  /opt/JACO2SDK/RobotConfiguration then execute it
On windows C:\Program Files (x86)\JACO2SDK\RobotConfiguration

And let me know if this will solve your problem.

https://drive.google.com/open?id=17U1-6N4qNT4kJ06rAM5LPpjTvrV0p0kL

Sincerely,
Sylvain

**Comment by robertbeach** [comment]
Hi,

It seems a little better. I am no longer getting large number (> 30) of points when moving 3" but I still regularly get 15-30 points that cause the arm to move in some odd ways in order to move 3" horizonatally left or right. 

For when the point count is 20 or more, I am still seeing the arm stop prematurely and/or in some odd pose, occasionally generating a collision with external structures that are defined as collision objects. 

I am also seeing the need for multiple replan steps in order to achieve 1.5cm accuracy (defined as the sum of the absolute difference between the goal and actual location of all three dimensions). Most of the time (80%) I require at least one replan to meet the 1.5cm goal. Sometimes I require 2 or 3 replans. 

At this point my biggest concern is the failure of the arm to reach the target position, sometimes by a large amount. I am testing now and on one movement the cummulative error was 40cm, another one was 35cm. In both cases the number of points in the initial move was 25-30. It  took 2 replan steps to get the arm where I wanted. As I noted above, at other times it collides with an external structure because it moved in an incorrect way. 

Any ideas on why the movement stops early and/or goes astray?

**Comment by sbrisebois** [comment]
The procedure Is intended to re-configure the ARM, it will not affect the number of points generated to reach a destination by ROS. You must run the procedure when the ARM is connected by USB on a PC and ROS is not running (to avoid conflict when sending the command). Then sending multiple points may not be a problem anymore.

Another reason that may explain the current behavior, is that it's necessary to add a 5ms delay between each command sent to the Jaco (internal process time) to avoid communication buffer overflow. Without this delay, sending multiple commands consecutively may cause this kind of behavior. Have a look at this and let me know if that help.

If still have problem with that, may you send me your code, so I can reproduce it and check for the solution.

Sincerely,
Sylvain

**Comment by robertbeach** [comment]
the routine kinova_joint_trajectory_controller.cpp sends a new command every 0.01 seconds (100Hz) and so that should cover the 5ms delay. 

However, I am filtering out (i.e. requesting a new plan) anytime I get a point count beyond 30. Most of the time I  get 10 points but whenever the count is higher than 10 I get a very large on the first movement. For example a point count of 26 yielded a 0.3 m cummulative error (sum of absolute errors in all three dimension). A point count of 29 yielded a 0.6m (!) cummulative error. Even a point count of 11 can yields  .1m error.  As long as can get 10 points, the arm seems to complete the planned trajectory. Any more than that and the trajectory goes wrong.

I am also finding that the arm generally (~90% of the ) overshoots the goal an average of about 1cm. If it goes left, it often goes 1-2cm too far left( ditto up, down, right). When I replan after the initial movement the cummulative error is about 5mm.

**Comment by robertbeach** [comment]
some more data, point count vs cummulative error. The errors are an average of for each point count

11p: 0.136
12p: 0:034
17p: 0.31m
18p: 0.39 m
19p: 0.42m
25p: 0.63m
26p: 0:67m
30p: 0,70m

In comparision for 10p trajectories (95%+ of the plans), typical errors for the first movement is about 0.017m, after a replan the error drops to about 5-6mm.

**Comment by martine1406** [comment]
Hello. Sorry I will not be able to answer very often as I am a new mother and my newborn keeps me very busy.

The behaviour you are describing would need more investigation. Have you ever tried to echo the trajectories sent my MoveIt to check if they make sense? Would you be able to provide an example of a 25-30 p trajectory?

The number of points in a trajectory depends on the planner (Trac IK in this case). We cannot really help you with that because we haven't designed this planner. Maybe you could try to search and post on MoveIt forums or try to look online for more information on the planner. 

Otherwise, I would recommend you try to follow the whole chain from Moveit to the robot. MoveIt sends its plan to [ joint_trajectory_action_server.cpp](https://github.com/Kinovarobotics/kinova-ros/blob/d2876ad92c075dda8d8ebd7663712046641a30ea/kinova_driver/src/joint_trajectory_action/joint_trajectory_action_server.cpp),, which publishes on "/"+ robot_name + "_driver/trajectory_controller/command. [kinova_joint_trajectory_controller.cpp](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_joint_trajectory_controller.cpp) listens to this topic and talks to the robot via its API using angular velocity commands. 

I hope this helps. Starting from there, my colleagues might be able to give you more elaborate explanations. 
All the best,
Martine

**Comment by robertbeach** [comment]
Hi Martine

thanks for taking the time to look my problems. 

As I noted in the prior post, I basically have two problems. The first is that anytime there are more than 10 points in a trajectory, arm movement becomes erratic and unreliable. Much of the time the arm fails to reach its target position, although driver output indicates that all the points in the trajectory have been processed. These larger point count trajectories seem correct (their final coordinates are what is wanted) but the arm fails to follow them. The more points there are, the larger the cummulative error of the arm. On occasion the arm will go completely out of the trajectory and collide with an external structure that it should avoid.  Sometimes it works okay but most of the time is does not. I can filter out trajectories with more than 20 points but sometimes moveit will not provide any 10 point trajectory and so I have no option but use the larger point trajectory. In such cases it can take 3-4 replan cycles to reach the desired target. 

From the outside, it looks like some arm commands are getting lost but that is just my observation.

The second problem is that  the arm generally (> 80 % of the time) overshoots the target by 1-2cm if the movement is more than 8-10cm . If I replan (and remove)  to the original goal to fix the overshoot, I can reach the target accurately (a few mm of error).  However fixing the overshoot takes time and effort and seems a symptom of some other problem.  

If you have any ideas as what is causing these problems and how to fix them I would really appreciate it as my project is currently sort of stuck here. 

Thanks - Bob

**Comment by sbrisebois** [comment]
Hi Bob,

Sorry for the delay on the answer, it's a very busy time for us now. I'm still working on your problem to find a solution. I didn't forget you, but I don't have the solution right now. It take time to reproduce the setup and the issue. As soon as I have a solution I'll notice you.

Thankyou for your patience.

Sincerely,
Sylvain

**Comment by martine1406** [comment]
Hi all

for the first problem, I am not sure what is causing it. This would need more investigation and debugging (where would the arm commands be lost? after being processed by [kinova_joint_trajectory_controller.cpp](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_joint_trajectory_controller.cpp)? Or before?)

For the second problem, I invite you to have a look at this issue: #115 and get inspired by the solution in #116. Indeed, Moveit sends a trajectory with time stamps, joint position, joint velocities and joint accelerations. But the robot does not have the capability to receive and execute this kind of trajectory; it only accepts series for points with no timestamps and series of velocities, which correspond toposition increments processed every 10 ms. [kinova_joint_trajectory_controller.cpp](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_joint_trajectory_controller.cpp) "solves" this problem by sending the same velocity command between two consecutive timestamps. e.g. if you receive a trajectory with three points from moveit (you therefore have timestamp 1, 2 and 3 and you have joint position, joint velocity and joint acceleration 1,2 and 3), this code will send joint velocity 1 during time = timestamp 2 minus timestamp 1, then send joint velocity 2 during time = timestamp 3 minus timestamp 2). This is not very accurate for those reasons: it's open loop and it is not really true that the velocity stays constant between two trajectory points from moveit. Replanning can indeed help to obtain a more accurate result. I know it is not an ideal situation, but this node needed to be designed quite quickly, so it probably misses some fin tuning. If you have ideas on how to improve the [kinova_joint_trajectory_controller.cpp](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_joint_trajectory_controller.cpp) node and want to submit a pull request, we'll be pleased to review it.

**Comment by alexvannobel** [comment]
Hi @robertbeach ,

I looked into the [kinova_joint_trajectory_controller.cpp](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_joint_trajectory_controller.cpp) node and, basically, as Martine explained, it is an open-loop controller that works with velocities and durations. 
Moreover, the controller, by design, always overshoots a bit the duration of the movement to reach a given point. It is only a few milliseconds, but over a large number of points, the error adds up and can become quite large. 
I created the [dev/reduce-overshoot-follow-joint-trajectory](https://github.com/Kinovarobotics/kinova-ros/tree/dev/reduce-overshoot-follow-joint-trajectory) branch.
Essentially:
- The controller now calculates if the next duration will be reached within the next timer cycle, and adjusts joint speed if so.
- I added a few debug messages to let you know if you had an overshoot for one point. 

I could not reproduce your first issue on an arm here at Kinova: real trajectories seem to follow the MoveIt plan accurately and no erratic behaviour was observed. I could reproduce your second issue, though, and I suggest :
- You can test with the [dev/reduce-overshoot-follow-joint-trajectory](https://github.com/Kinovarobotics/kinova-ros/tree/dev/reduce-overshoot-follow-joint-trajectory) branch at least to better debug your problem. 
- You can also monitor the dropped messages with rqt_graph for a given subscriber.
- You can also try the [dev/improved-precision-moveit-plan](https://github.com/Kinovarobotics/kinova-ros/tree/dev/improved_precision_moveit_plan) branch (which makes the controller closed-loop), but I have to warn you that this branch is a third-party contribution and was not tested by us. It may be broken. 

Hope this helps, 

Best, 
Alex

**Comment by robertbeach** [comment]
Hi Alex

I tried out your overshoot trajectory controller branch and have results.

Just using your version the overshoots were reduced from 42% of movements to 32%.

I then added some additional adjustments on joints 1-3 as follows:

            joint_velocity_msg.joint1 *= (adjust_factor * f);
            joint_velocity_msg.joint2 *= (adjust_factor * f);
            joint_velocity_msg.joint3 *= (adjust_factor * f);

if f =0.8 and is only applied to joint 1, overshoot drops to 25%

if f =0 .5 and is applied to all three joints, overshoot drops to 14%

if f =0 .4 and is applied to all three joints, overshoot drops to 11%

if f = 0.3 and is applied to all three joints, overshoot drops to 8%

if f = 0.1 and is applied to all three joints, overshoot drops to 5%

It seems the larger joints have enough momentum that one can almost "stop" them early and they will still continue to the proper position. In any case 95% is good enough for me. 

thanks for you help

Bob

**Comment by alexvannobel** [comment]
Hi @robertbeach ,

Glad to hear the fix worked for the overshoot problem!

Did you have any luck with the erratic trajectories problem? It indeed is weird that all 10-point trajectories work and all above 10 are erratic. 
I would suggest you to look at all the subscribers in the chain (the action server, the controller, the robot driver) to see how they are initialized in the C++ node implementations, especially in terms of queue size; maybe one of those subscribers start dropping messages at exactly 11 and that could explain the behaviour you're seeing. 

Since the FollowJointTrajectory and GripperController action servers are two different implementations, I do not personally think your custom gripper+fingers and URDF cause this problem, but it could be worth investigating if you don't have any more clue.

Hope this helps,

Best, 
Alex

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a years, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
