### ISSUE TITLE
Where/How are the cartesian coordinates in tool_pose calculated

### ISSUE THREAD

**Issue by robertbeach** [Kinovarobotics/kinova-ros#210]
I have been trying to understand how the cartesian coordinates that are reported in the tool_pose topic are generated. Do they come from the robot itself or are they generated in the drivers. I have been looking in the latter and cannot find anything that looks like it. If they are generated in the robot what is assumed about the dimensions of the arm? I am using my own end-effector that has different dimensions than either the two or three fingered units that come with a Jaco arm. Do the cartesian coordinates refer to the end effector or two the last arm link (or something else). 

Thanks

Bob

**Comment by nsaif-kinova** [comment]
Hello Bob,
The positions are calculated in the base, they reflect the position of the end effector, please visit pages 72-90 to know the exact position of the end effector depending on your arm configuration.
You have also the option to add an offset on the end effector so it can match the position of your custom gripper.
Sincerely,

**Comment by nsaif-kinova** [comment]
The controller calculate the end effector position according to the position I sent to you in the guide previously (as if there is a gripper attached)
The inverse kinematic is calculated in the controller. However you can still use moveit or other software to calculate the inverse kinematic outside the controller and send angular positions to the joints instead of cartesian positions.
Sincerely,

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a years, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
