### ISSUE TITLE
mico cannot move using moveit

### ISSUE THREAD

**Issue by wangxian4423** [Kinovarobotics/kinova-ros#234]
Hi,I'd like to ask a question.While I`m using the mico m1n6s300 with the moveit,I find it cannot execute though the result shows Executed.It looks like this:
![image](https://user-images.githubusercontent.com/39849016/56708263-9d8ec400-674e-11e9-8864-0de664e975da.png)
and I find the rqt_graph show this:
![image](https://user-images.githubusercontent.com/39849016/56709451-f7de5380-6753-11e9-9936-f28407a7d9cc.png)
The /m1n6s300_joint_trajectory_action_server publish a topic called /m1n6s300_driver/trajectory_controller/command and it works well.Howerer,it seems like no node has deal with this topic,so the arm cannot be command.
So what can I do to solve this problem?
Thank you very much if you can help me~

**Comment by RalphChahine** [comment]
Hi, I have tested mico on my part to try and reproduce the error. However, all worked fine for me. I was able to control the arm through moveit with no problems on both Ubuntu 14 and Ubuntu16.  Here are the commands that I used : 
1) roslaunch kinova_bringup kinova_robot.launch kinova_robotType:=m1n6s300
2) roslaunch m1n6s300_moveit_config m1n6s300_demo.launch

Is there an error that appears on the terminal when you do the command 1)?
Is there an error when you do the command 2)

If there is, please send me what the errors are so I can troubleshoot your issue

Ralph

**Comment by wangxian4423** [comment]
Thanks for your reply,well,there is an error when I  do the command 2)
`[ERROR] [1556242694.061319794]: SpinnerMonitor: single-threaded spinner after multi-threaded one(s).Attempt to spin a callback queue from two spinners, one of them being single-threaded.
In the future this will throw an exception! Only allowed for backwards compatibility.
`
Besides,the joystick is Flashing green light like this and I cannot use the joystick to control the arm.
![image](https://user-images.githubusercontent.com/39849016/56778294-333a5a00-6808-11e9-87dc-a5d533364297.png)
Though the arm can be control using the  GUI form the SDK.

**Comment by RalphChahine** [comment]
You are facing a boot loader issue since you cannot control the arm with either the joystick or ROS and the green lights are flashing on your jostick. 
You will need the latest version of Development Center available on our website. Here is the link: 

https://www.kinovarobotics.com/en/knowledge-hub/all-kinova-products 
and choose "KINOVA® SDK GEN 2 Ultra lightweight robot 1.5.1".
Follow the release notes (RN) document to install the software properly.
Power-down the arm and short-circuit the 2 pins in the joystick connector as shown in the picture below. 
![image (1)](https://user-images.githubusercontent.com/47039865/56807204-21eb5080-67fc-11e9-8560-c50368fc42d9.png)

Connect the arm to the computer via USB, power-on the arm and launch Development Center.

·  In the top right corner, the mention "BOOTLOADER" should be displayed. 

·  Click on General Settings and go to the Update tab.

·  Click on Browse and choose the firmware version attached below for your mico 6DOF robot that you can download with this [link](https://drive.google.com/open?id=1DNkY1wlWMtOHItbMyxAOlY72H8vc5rV9) 

·  Click on Update (this step can take up to 2 minutes)

·  Once the update is completed, power down the arm and remove the short circuit from the joystick pins.

·  Power on the arm.

You should now be able to control the arm using the joystick. Now please make sure the developement center is closed and try to do the following two commands in your terminal   : 
1)roslaunch kinova_bringup kinova_robot.launch kinova_robotType:=m1n6s300
2)roslaunch m1n6s300_moveit_config m1n6s300_demo.launch

If there is still an error when you launch one of these two commands please let me know and I will help you :)

**Comment by wangxian4423** [comment]
Ok,Thanks for your help.Now I'm waiting for the Google  Disks Premission.
![image](https://user-images.githubusercontent.com/39849016/56843209-44e73480-68d0-11e9-8f57-dee18a1d4bcd.png)
And I'll try to update the firmware after that.Thanks!

**Comment by wangxian4423** [comment]
Well,things seems to be difficult....I did what you said and it showed updated completed, howerer, the green lights still flash and things don`t seem to be better. So what can I do?

**Comment by RalphChahine** [comment]
Hi wangxian,

could you please try to do the procedure again? I have tried it on my end on a mico that had the same problem you had and it worked. If it does not work after another attempt, it might be a hardware issue and you would have to consider sending the arm back at Kinova HQ for a fix.

Please let me know

**Comment by wangxian4423** [comment]
Well,thanks for your help,I tried it again and the joystick still flash the green light,may there is something wrong with the joystick.And this time I try the kinova-ros-master devel and the moveit works well.I see the rqt_graph
![image](https://user-images.githubusercontent.com/39849016/56936557-92f77480-6b2a-11e9-80c2-3f874366a400.png)
and maybe there is a bug in the kinova-ros-kinectic devel which I used before as the rqt_graph in this version is:
![image](https://user-images.githubusercontent.com/39849016/56936606-f1245780-6b2a-11e9-8341-7c1396f300a0.png)

**Comment by g1y5x3** [comment]
Hi,
I had a similar issue with MICO. My Ubuntu was 16.04 and I was running ros kinetic. And the particular branch I was using was from this branch [kinetic devel](https://github.com/Kinovarobotics/kinova-ros/tree/kinetic)

What I realize that in the kinetic branch, it has its own robot controller written as a python script in **kinova_driver/src/scripts**, more specifically, they set the topic statically as "/j2s7s300/follow_joint_trajectory". This explains why when I was using MICO, the robot didn't move. It was simply because that driver was not configured for it. They also changed the launch file in **kinova_moveit** that calls the python script that they created.

To solve it, I simply replaced the [kinova_joint_trajectory_controller.cpp](https://raw.githubusercontent.com/Kinovarobotics/kinova-ros/master/kinova_driver/src/kinova_joint_trajectory_controller.cpp) from the master branch and **catkin_make** again. And my MICO arm works as expected!

Hope that would help!

**Comment by Hubert51** [comment]
Can you give some more detail information? Currently, I only see `pid_traj_action_server.py` in kinova_driver/src/scripts. So what should I do to let my kinova arm execute the command? Do you mean I need to use `kinova_joint_trajectory_controller.cpp` from master to replace the same file in kinetic branch.
Thank you very much

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over 2 years, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
