### ISSUE TITLE
Unable to move jaco arm j2n6s300 in gazebo using ros_control

### ISSUE THREAD

**Issue by farahamirah** [Kinovarobotics/kinova-ros#255]
## Description

Hello. I am new to Gazebo. I have issue on moving robot arm jaco j2n6s300 in gazebo. I have tried to move the robot arm using gazebo_control but when i run the python script, the robot do nothing. I am using the kinova-ros package along with ROS Kinetic and Ubuntu 16.04.

I start my simulation with: 
roslaunch kinova_gazebo robot_launch.launch kinova_robotType:=j2n6s300
rosrun kinova_control move_robot.py j2n6s300

When i check the rqt_graph, the node 'move_robot_using_trajectory_msg' is not publishing any topic to the gazebo.
![rqt](https://user-images.githubusercontent.com/53845469/62591185-5abdba00-b901-11e9-9388-eaf074572301.png)

I have also tried to edit the home position in the python code move_robot.py but the robot still not moving. Am I missing something in here ?

## Version

ROS distribution : Kinetic. Ubuntu 16.04.

**Comment by alexvannobel** [comment]
Hi @farahamirah ,

You can look at the [Gazebo documentation](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_gazebo/Gazebo.md) we wrote for details on the Gazebo simulation.You have the good first step with 
```
roslaunch kinova_gazebo robot_launch.launch kinova_robotType:=j2n6s300
```
and normally the trajectory controllers should be loaded and started. 

If you ```rostopic list```, can you see the ```/j2n6s300/effort_joint_trajectory_controller/command``` topic? 
- If no, what's the output? 
- If yes, can you try to publish on it to see if the robot will move? It should.

The Python script only publishes once to this topic, so that's probably why you don't see it in rqt_graph.

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
