### ISSUE TITLE
Parameters about the actuator

### ISSUE THREAD

**Issue by RobotBT** [Kinovarobotics/kinova-ros#264]
We recently have met some problem with the inaccuracy of the motion of Kinova jaco2 (20cm
± 8mm). Does this kind of error normal? Then we search the parameter about kinova actuator and get some unfamiliar term.
([https://www.kinovarobotics.com/sites/default/files/AS-ACT-KA58-KA75%2B-UG-INT-EN%20201804-1.2%20%28KINOVA%E2%84%A2%20Actuator%20Series%20user%20guide%29_0.pdf](https://www.kinovarobotics.com/sites/default/files/AS-ACT-KA58-KA75%2B-UG-INT-EN%20201804-1.2%20%28KINOVA%E2%84%A2%20Actuator%20Series%20user%20guide%29_0.pdf))
Page 11, **_Absolute position sensor precision at start-up (before indexation)_** and **_Motion before position indexation_**
Would you please explain those for us?

Moreover, We also notice that once move our robot to a specific position and save the current angle position through Kinova SDK, if we shut down the robot and then sending the saved angle position as the joint angle command, there exits a bigger error in position compared with not shutting down the robot. Dose the shutting down process affecting the position repeatability

Thank You!

**Comment by alexvannobel** [comment]
Hi @RobotBT ,

First, for the inaccuracy issue, do you mean you get an 8mm error whenever you move 20cm?
For the terms in the data sheet:
- **Motion before position indexation**: The actuators have absolute position indexes to know where they are, but on boot-up they don't output a precise value. It is only once they have crossed their first index that they will be precise. The value in the table is the maximum movement they have to make before crossing that first index and being precise. 
- **Absolute position sensor precision at start-up (before indexation)**: This is the precision the actuator has before crossing the first position index. 

What is the exact sequence of events when you experience this behaviour? Do you move the arm to the given position, then reboot the arm, then send the position once again? Do you bring the arm back to the Retract or Home position, then reboot, then go back to the first position?

Because of the combined inaccuracy of all actuators, it is possible that the arm won't go to the exact same measured position when giving it a given position command.

Best,
Alex
