### ISSUE TITLE
Can't control Jaco j2n6s300 by effort / torque in Gazebo

### ISSUE THREAD

**Issue by PierreExeter** [Kinovarobotics/kinova-ros#301]
## Description

I can start the Jaco j2n6s300 in Gazebo and I can control the joints by position as explained [here](https://github.com/Kinovarobotics/kinova-ros/wiki/Gazebo). However, I cannot control the joints by efforts. When publishing efforts in the topic /j2n6s300/effort_joint_trajectory_controller/command, the robot moves according to joint angle positions, not joint efforts. How can I control the robot by joint efforts / torques?

## Version

ROS distribution : Melodic
ROS version: 1.14.5
Branch: master
commit: 592e90fda95abe607b1ac4635829e05d92a1a525

## Steps to reproduce

In terminal 1:

``` bash
roslaunch kinova_gazebo robot_launch.launch kinova_robotType:=j2n6s300
```
The robot is spawned in Gazebo.

Edit joint angles in move_robot.py
```
moveJoint ([0, 3.14, 3.14, 0, 0, 0],prefix,nbJoints)
```

In terminal 2:

``` bash
rosrun kinova_control move_robot.py j2n6s300
```

This works - the robot moves according to the angle positions specified in move_robot.py.

Now edit move_robot.py and replace

```
point.positions.append(jointcmds[i])
point.velocities.append(0)
point.accelerations.append(0)
point.effort.append(0) 
```

by

```
point.positions.append(0)
point.velocities.append(0)
point.accelerations.append(0)
point.effort.append(jointcmds[i]) 
```

The robot still moves according to joint angle positions, not joint efforts (it seems that point.position [0, 0, 0, 0, 0, 0] has priority over point.effort in the message sent).

## Expected behavior

I expect the robot to move its joints according to the torque values sent, not according to the angle positions.

**Comment by alexvannobel** [comment]
Hi @PierreExeter ,

In fact, since the `effort_joint_trajectory_controller` is of type `effort_controllers/JointTrajectoryController`, you won't be able to command torques directly to it. I think the `point.effort` value here means the joints should reach certain torques when getting to that waypoint.

By looking a bit more into [the ros_control config file](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_control/config/j2n6s300_control.yaml) and in [the ROS Control documentation](http://wiki.ros.org/ros_control) (see section 2 for Controllers), we see that a ROS Control controller is actually split in two parts : what is sent to the robot (here Gazebo) and what is the ROS input. In the config file, the type of the `effort_joint_trajectory_controller` is `effort_controllers/JointTrajectoryController`. This means the controller actually sends torques to Gazebo, but receives Joint Trajectories from ROS (which is why positions dominate over efforts in the `moveRobot.py` script).

We didn't add a controller which sends direct torques to the Gazebo, but we have controllers who take positions as input. If you want to implement it, my advice would be:
- Copy the `joint_*_position_controller`'s and rename them to `joint_*_effort_controller`
- Change their type to `effort_controllers/JointPositionController` (to be double-checked, but I think it's the syntax)
- Not sure if the PID values are needed, since the controller will essentially forward the command to Gazebo, you would have to check that

At that point, you would have torque controllers for each joint, which you could spawn and load using the default ROS Control tools.

Hope this helps,

Alex

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
