### ISSUE TITLE
setPlannerParams

### ISSUE THREAD

**Issue by s265452** [Kinovarobotics/kinova-ros#355]
Hi everyone,
I'm a beginner in ROS. I have some difficulties by settting Planner Params to a PlannerId.
These are my code lines:

  group_-> setPlannerId("RRTConnectkConfigDefault");

  struct	str{std::string keys;std::string values;std::string descriptions;} par;
  	par.keys="range";
	par.values="0.01";

  group_-> setPlannerParams("RRTConnectkConfigDefault",robot_type_,par, true);

I have this error:

 error: no matching function for call to ‘moveit::planning_interface::MoveGroupInterface::setPlannerParams(const char [25], std::__cxx11::string&, const char [5], bool)’
   group_-> setPlannerParams("RRTConnectkConfigDefault",robot_type_,par, true);
                  
Waiting for your answer.

**Comment by felixmaisonneuve** [comment]
Hi @s265452,

Is this related to our Kinova-ros repo? I don't think this is the right place to ask such question. 

Other than that, I feel your error is quite explicative. `setPlannerParams` takes 4 arguments, notice the 3rd one. It is supposed to be a `const char[5]` but you give it `par` (which is your custom struct). Maybe you wanted to use `par.keys` instead?

Anyway, since this is not something related to Kinovarobotics, I will close this issue. Maybe you should ask this on the ROS or the moveit github page.

Regards,
Felix
