### ISSUE TITLE
Problem using torque control in ros

### ISSUE THREAD

**Issue by maomaoxiong123** [Kinovarobotics/kinova-ros#357]
I would like to control the arm in torque control mode without gravity compensation. I have tried to change torque_parameters, 'publish_torque_with_gravity_compensation' to false or true, but it's of no use.
If there is any method to disable gravity compensation function in torque control mode? It would be appreciated if anyone can help.
I use Ubuntu18.04, melodic, jaco2

**Comment by felixmaisonneuve** [comment]
Hi @maomaoxiong123,

Are you able to control the arm in torque control mode with gravity compensation? Is the problem strictly related to `publish_torque_with_gravity_compensation` not doing anything or is torque control mode not working at all?

Also, we provide a small application `TorqueConsole` that can help when playing with torque control mode. Sometimes it is easier/faster to test different things with it instead of changing the code. 

To use `TorqueConsole` to put the arm in torque console mode, follow these steps : 

```
1.Put your arm in candle-like position (every joint in a vertical position)
2.Open Development Center (JacoSDK). In the "Monitoring" section, every actuator should have a value close to 180° in the
   Command and Position columns. Every actuator should also have a Torque value between -10 Nm and 10 Nm.
3.Open "Advanced Settings". In the section "Torque zero", select "apply to all". The "Monitoring" section should now show
   Torque values close to 0 for each actuator.
4. Open TorqueConsole.
5. Test your connection with the "Test Connection" button. It should change to "Good Connection"
6. Change the "Safety Factor" to 1
7. Click "Switch Torque Control" button.
```

Regards,
Felix

**Comment by maomaoxiong123** [comment]
Hi @felixmaisonneuve,
The torque control mode can work well, but the mode is in gravity compensation as default. I follow the REAMME.md to disable gravity compensation by changing parameter 'publish_torque_with_gravity_compensation', but it did not work.
The problem I focus on is how to disable gravity compensation in torque control mode.
By the way, 'TorqueConsole' works well but also in gravity compensation as default.

**Comment by felixmaisonneuve** [comment]
This parameter is only to change the value published by the joint_torque_publisher (on topic `out/joint_torque`) and will not change the behaviour of your arm. 

What you could do is change the gravity vector to [0,0,0] (e.g. in TorqueConsole). I think this is probably what you are trying to achieve. 

Best,
Felix

**Comment by maomaoxiong123** [comment]
Hi @felixmaisonneuve,
The method to change the gravity vector to [0,0,0] using TorqueConsole did not work. It will change to position mode immediately.

**Comment by felixmaisonneuve** [comment]
Hi @maomaoxiong123,

I am not sure what you are trying to do is possible. 
The user guide says 
>The first safety is that the arm will not switch from
position mode to torque mode unless the torque read by the actuators and the gravity torques computed
by the gravity model inside the robot are too different. On reboot, the arm will always go back to position
mode

I think, because of that, the arm won't be able to switch in torque mode. There will always be a mismatch between the robot gravity model and the actual torque values. 

This is probably why changing the gravity vector didn't work.

Sorry For the inconvenience.

I will close this issue, but if you still have questions, feel free to ask them or reopen the issue

Regards,
Felix
