### ISSUE TITLE
After switching to torque control mode, the torque cannot be controlled

### ISSUE THREAD

**Issue by Yang12308** [Kinovarobotics/kinova-ros#358]
when I use kinova j2n6s300 
After switching to torque control mode ,using the following commands
`rostopic pub -r 100 /j2n6s300_driver/in/joint_torque kinova_msgs/JointTorque "{joint1: 0.0, joint2: 0.0, joint3: 0.0, joint4: 0.0, joint5: 0.0, joint6: 1.0}"`
No change in torque sensor data and no movement of the robot arm
using the following commands
`rosrun kinova_demo gravity_compensated_mode.py j2n6s300 `
I can not  move it by hand with very little resistance and
the Safety factor is 1

**Comment by felixmaisonneuve** [comment]
Hi @Yang12308,

It is often hard to change an arm to Torque Control mode the first time. I suggest using the Torque Console to get it working the first time, because I think it is faster to use. 

Follow these steps : 
1. Put your arm in candle-like position (every joint in a vertical position)
2. Open Development Center (JacoSDK). In the "Monitoring" section, every actuator should have a value close to 180° in the Command and Position columns. Every actuator should also have a Torque value between -10 Nm and 10 Nm.
3. Open "Advanced Settings". In the section "Torque zero", select "apply to all". The "Monitoring" section should now show Torque values close to 0 for each actuator.
4. Open TorqueConsole.
5. Test your connection with the "Test Connection" button. It should change to "Good Connection"
6. Change the "Safety Factor" to 1
7. Click "Switch Torque Control" button.
Your arm should now be in torque control mode 

Once this is working, try to run `gravity_compensated_mode.py` again.

Publishing joint torques while the arm is in torque control mode might move your joint (if the torque is big enough). If your joint doesn't move, I suppose it will be easier to move the joint in one way (if you apply torque in the same direction as your torque command) and harder in the other way (since you also have to componsate your torque command).

Try using TorqueConsole and let me now how it goes.

Regards,
Felix

**Comment by Yang12308** [comment]
Thanks

I eventually found out that it was a problem with the arm and that the torque control was not working with the previous arm

thank you for your help

**Comment by Yang12308** [comment]
Firmware is up-to-date, maybe hardeware issues

**Comment by felixmaisonneuve** [comment]
What make you think this is hardware related?

If you think this is a hardware issue, you probably need to contact support at support@kinova.ca
