### ISSUE TITLE
Velocity signal

### ISSUE THREAD

**Issue by s265452** [Kinovarobotics/kinova-ros#381]
Hi everyone,
I'm using:
Kinova a j2s7s300 manipulator
ROS Distro: Melodic
Ubuntu 18.04

I've some doubts about signals published on the topic /joint_state.

I wish to know:
1- How is the /joint_state/position[]  detected?
2- How is the /joint_state/velocity[]  detected?
3- I wish to know the reason why the signal FeedBack has this behaviour. I clean the singnal with a lowpass filter @5Hz Frequency

![image](https://user-images.githubusercontent.com/88098137/154678075-be04f3c7-49ca-4cb4-ba8f-b34c2872adfa.png)

If I derive the /joint_state/position[] I have this behaviour. These are very different

![image](https://user-images.githubusercontent.com/88098137/154678539-336c4d9a-9a34-42c2-b4bf-92cc52be2222.png)

Waiting for your answer.
Francesco

**Comment by felixmaisonneuve** [comment]
Hi @s265452,

The `/joint_state/position[]` is coming directly from the actuator's position. 

The `/joint_state/velocity[]` is also coming directly from the actuator's position, but this one is a bit different.
This was slightly covered in this [issue](https://github.com/Kinovarobotics/kinova-ros/issues/202#issuecomment-853589734).

To summarize, the firmware is constantly adjusting its speed to produce a steady velocity. Joint speed, at any instant, for example, because of motor tuning (PIDs) criterias, inconsistent friction on the joint, inconsistent current, worn out components...

A different PID tuning could help mitigate that, but Kinova does not provide a tool to tune the PIDs. 

You do have access to functions that modify the values via the API.
 However, it is not recommended to do so because it could severly damage your robot and it would not be covered by your garanty as stated in the [User Guide](https://drive.google.com/file/d/1xQbkx1-v3SfAentKR9f3p3c2SVdViyQl/view?usp=sharing) (pages 23-24) :
>Setting these parameters out of the suggested range can
severely damage the robot and is not covered by the
warranty.

This explains why your signal feedback looks like this. The "instant" velocity does not represent the overall velocity of the joint.

This is the normal behaviour. I am not sure there is something you could do to about it.
Is this a problem for your use case?

Regards,
Felix

**Comment by s265452** [comment]
Thank you for your reply.

I read the User guide Manual. It says that actuators are servomotors. Each motor has one position trasducer and one accelerometer.

So, how is detected the velocity feedback?

By integrating accelerometer signal ?
By deriving position signal? 

I have another question.
I set AddTimeParametrization in ompl_planning_pipeline.yaml.

`name="planning_adapters" value="default_planner_request_adapters/AddTimeParameterization`

Reading this paper,  
[ParabolicBlends.pdf](https://github.com/Kinovarobotics/kinova-ros/files/8098452/ParabolicBlends.pdf)

I thought that `/j2s7s300_driver/in/joint_velocity` should have been a trapezoidal law velocity, but it is a step law.
How is it possible? Am I wrong?

**Comment by felixmaisonneuve** [comment]
Velocity is computed by Actuators using the position signal. They do something like `(currentPosition-lastPosition)/(currentTimeStamp-lastTimeStamp)`.

For your second question, I am confused. 
`AddTimeParametrization` is already set by default in ompl_planning_pipeline.launch.xml : 
https://github.com/Kinovarobotics/kinova-ros/blob/93f66822ec073827eac5de59ebc2a3c5f06bf17f/kinova_moveit/robot_configs/j2s7s300_moveit_config/launch/ompl_planning_pipeline.launch.xml#L8

The paper you linked is about trajectories to avoid stopping at every waypoint. I am not sure how this would apply with joint_velocity commands.

I am also not sure what is the relation with your paper and the trapezoidal/step laws.

**Comment by s265452** [comment]
Ok Felix, thank you for your reply.

AddTimeParameterization apply an  "Iterative Parabolic Time Parameterization" .

Do you know other references about this Algorithm?

The file attached before is the only one I found.

**Comment by felixmaisonneuve** [comment]
Of course!

You can look at the MoveIt documentation about Time Parameterization [here](http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/time_parameterization/time_parameterization_tutorial.html)

This page links to a bunch of other documentation pages and github repositories with examples on the different Time Parameterization (and a lot more). 

If you are interested in the implementation of the default Time Parameterization, you can look at it on [github](https://github.com/ros-planning/moveit/blob/melodic-devel/moveit_core/trajectory_processing/src/iterative_time_parameterization.cpp) (which is linked in the documentation page).

I would start there. You can probably find anything you want to know in there.

Hope this helps,
Felix

**Comment by s265452** [comment]
Ok Felix,
Thank You, I was looking for academic articles.

I had to read the entire code.
