### ISSUE TITLE
Unable to read joint state more often that 10 Hz?

### ISSUE THREAD

**Issue by fredrikbaberg** [Kinovarobotics/kinova-ros#85]
I need to read the joint state more often than the 10 Hz being default in kinova_robot.launch. To increase this, I've found that the parameter "/j2n6a300_driver/status_interval_seconds" can be changed. When using a value corresponding to 60 Hz instead I get a very non-smooth motion of the arm.

How can I read the joint state at more than 10 Hz, without affecting sending joint velocity commands?
I'm aware I can use the C++ library to query the joint state through the API, however that means I loose connectivity from the kinova_robot launchfile drivers, and have to re-write more of the functionality.

**Comment by soli7** [comment]
Look at the function [here](https://github.com/Kinovarobotics/kinova-ros/blob/24b856ad273b071bbd909ea0e7e2c2ee397b0e1d/kinova_driver/src/kinova_arm.cpp#L485)

Since you are using velocity control (sending commands every ~10ms) and you want to read joint state at a faster rate too, you should reduce the number of values requested from the arms. For example - if you do not need tool pose or finger position or torques comment them out. THis is a USB delay issue, soon we will have a Ethernet release and communication will be faster.
