### ISSUE TITLE
original vs. estimated parameters for gravity compensation

### ISSUE THREAD

**Issue by rezaahmadzadeh** [Kinovarobotics/kinova-ros#91]
The number of COM parameters in the yaml file is 27 while the estimated gravity compensation parameters are 19 on a 7DOF. Is this an issue? 
If the `use_estimated_COM_params` is set to `true`, where should we place the file including the estimated parameters?

**Comment by martine1406** [comment]
Hi Reza. I think I answered you be e-mail. Here was our discussion: 

me: you can use the COM parameters. Just fill in the 19 first parameters. 

you: Thanks for the quick response. Should the remaining 9 parameter stay 0 or removed?
Right now either with 19 parameters or 28 parameters, the robot does not switch to torque mode (cannot be moved manually). There is no error, it just waits a little bit and then switches to the Cartesian mode. Is the service to call?

me: The other parameters can stay zero.
What service are you calling?

you: I am using the node `gravity_compensated_mode` as instructed in the readme file.
After launching the bring-up, I execute the node
rosrun kinova_demo gravity_compensated_mode.py j2s7s300
The first two steps (moving the arm to the candle pose and torque-zeroing) execute successfully. However, when it switches to the torque control mode the robot cannot be moved and after a while it switches back to Cartesian mode. There is no error during the process.
My question: Do we need to call an extra service or another node to be able to interact with the robot (zero torque + gravity comp)? If not, why the robot does not switch to torque mode?

me: Have you called the service /j2s7s300_driver/in/set_torque_control_parameters?
I know that this service updates the torque control parameters, including the optimal gravity parameters you are trying to send. 

you: Yes,
rosservice call /j2s7s300_driver/in/set_torque_control_parameters
works fine and it shows the parameters set.
And the estimated parameters look like this, which works fine with the API

you: I tested different combination of settings,
With
use_estimated_COM_parameters: false
There would be no error, I guess because it is using the MANUAL-INPUT for the gravity compensation
With
use_estimated_COM_parameters: true
The gravity comp mode does not work both with all zeros and with optimized parameters.
In some instances, I received error 2005, I will check more tomorrow and let you know.

me: Don't worry about this error. The parameters are still updated fine. Its because we send more data than needed to the DSP, and it replies that it got too many data, but it still gets the data it needs. We'll have to fix this in future releases.
In my case, I also get the error when sending use_estimated_COM_parameters: false. But I work with a 6 dof and I think one of my colleague had brought a small fix on the 7 dof, hence the absence of the error message.
